### ISSUE TITLE
Sprach-, Hilfe-, und Mode-Auswahl Buttons verrutschen auf kleinen Bildschirmen

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#1]
Auf kleinen Bildschirmen werden die Icon Buttons so dargestellt:
![image](https://github.com/user-attachments/assets/fb6dfea6-82ad-4bf9-a5db-0673d33c72bc)

**Comment by Ali-GeoFZ** [comment]
Das trifft auch auf das neue Button zu
![Image](https://github.com/user-attachments/assets/fea28a45-0abe-45b9-86b0-35d38e9a83f4)

**Comment by Ali-GeoFZ** [comment]
- [ ] Sprach-, Hilfe-, und Mode-Auswahl Buttons
- [ ] Feedcack Button

**Comment by McNamara84** [comment]
Hat @Ali-GeoFZ bereits erledigt. Ich schließe mal.
