### ISSUE TITLE
Fehlermeldung bei ausgeschaltetem JavaScript

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#110]
In den meisten Browsern kann JavaScript deaktiviert werden. Dadurch wird die Validierung im MDE2 natürlich ebenfalls nicht funktionieren und Nutzende können Daten einfach so speichern. Tatsächlich werden die Daten von der Datenbank jedoch nicht gespeichert, weil z. B. falscher Datentyp.
Grundsätzlich ist das eher unproblematisch, aber Nutzende erhalten dann auch keine Fehlermeldung, dass ihre Daten nicht gespeichert bzw. versendet wurden.
Hier wäre wohl eine Fehlermeldung eine tolle Sache, die den User darauf hinweist, dass er JavaScript am besten aktiviert um den Editor besser nutzen zu können und eine weitere Fehlermeldung, die Nutzenden meldet, dass ihre Daten eben nicht vernünftig gespeichert wurden.

**Comment by McNamara84** [comment]
Ich hab mich mal umgeschaut, wie andere dieses Problem lösen. Dabei bin ich auf das `<noscript>`-Element in HTML5 gestoßen, das ich bisher nicht kannte. Hier die [Doku dazu auf w3schools](https://www.w3schools.com/tags/tag_noscript.asp).
[Laut Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) funktioniert das in den für uns relevanten Browsern.
Wenn keine anderen Ideen dazu eingehen, würde ich da heute im Laufe des Tages umsetzen.

**Comment by McNamara84** [comment]
Umgesetzt. Was meint ihr, @jaFHP und @Ali-GeoFZ , reicht dieser Hinweis aus oder wollen wir noch einen Schritt weitergehen? Mit etwas CSS-Gefrickeln und Mehraufwand könnten wir auch noch das Formular unleserlich (blurry?) machen damit es nicht benutzt werden kann... Oder wollen wir darauf vertrauen, dass Forschende den Hinweis verstehen und umsetzen werden?

**Comment by Ali-GeoFZ** [comment]
@McNamara84, Ich gehe davon aus, dass die Forschenden den Hinweis verstehen werden, da sie JavaScript ja selbst deaktiviert haben. Ich finde den Hinweis auch gut. Ich habe aber eine Frage: Was passiert bei dir, wenn JavaScript in deinem Browser deaktiviert ist und du trotzdem auf "Save" klickst? Bei mir wird dann
"Not Found
The requested URL was not found on this server." angezeigt. Gehört das auch zur Umsetzung?

**Comment by McNamara84** [comment]
> @McNamara84, Ich gehe davon aus, dass die Forschenden den Hinweis verstehen werden, da sie JavaScript ja selbst deaktiviert haben. Ich finde den Hinweis auch gut. Ich habe aber eine Frage: Was passiert bei dir, wenn JavaScript in deinem Browser deaktiviert ist und du trotzdem auf "Save" klickst? Bei mir wird dann "Not Found The requested URL was not found on this server." angezeigt. Gehört das auch zur Umsetzung?

Ah, stimmt! Der Event Listener, der den Klick auf die Buttons entgegen nimmt, ist ja auch in JavaScript! Sehr gut, lieber @Ali-GeoFZ , und vielen Dank für den Hinweis! Dann ist meine Frage natürlich obsolet, denn die potenziell invaliden Daten können ja dann gar nicht erst in die Datenbank gelangen.
