### ISSUE TITLE
Hilfebuttons bei dublizierten Zeilen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#118]
In den Abschnitten **Originating Laboratory** und **Funding Reference**  haben die Formularfelder der dublizierte Zeilen Hilfebuttons.
Das ist inkonsistent zu den restlichen Abschnitten, und, noch wichtiger: Diese Buttons funktionieren nicht.
Ich würde daher vorschlagen sie zu entfernen :)

**Comment by McNamara84** [comment]
Danke für dein Feedback! Nehmen wir sehr gerne mit in das nächste Sprint Planning.
