### ISSUE TITLE
Im Titel sind keine Satzzeichen .-_()""!? erlaubt

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#119]
Ich glaube aber, sie müssten erlaubt sein. Wenn es einen guten Grund dafür geben sollte, sollte die Info angepasst werden. Im Moment steht da als Hinweis "Please provide a title", was bei Nutzer:innen zu Unverständnis führen kann.

**Comment by McNamara84** [comment]
Du hast natürlich Recht, dass da auch bestimmte Sonderzeichen erlaubt sein sollten. Danke für den Hinweis! @Ali-GeoFZ übernimmt das.

**Comment by Ali-GeoFZ** [comment]
@jaFHP, danke für den Hinweis! Erledigt!
