### ISSUE TITLE
Roles-Felder als Tagify Elemente initialisieren

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#12]
Design wäre dann einheitlicher, man könnte nur die Whitelist erlauben.

**Comment by McNamara84** [comment]
Inzwischen wurde uns die Entscheidung wohl abgenommen. Laut [GitHub-Repository](https://github.com/harvesthq/chosen) wurde die Entwicklung von Chosen wohl auch langfristig eingestellt. Ein Umbau wird wohl für unser Projekt langfristig notwendig werden.

**Comment by McNamara84** [comment]
Sehr gut, wenn das funktioniert hat! Denkst du bitte noch daran im selben Branch die ReadMe anzupassen?

**Comment by McNamara84** [comment]
Ah, und natürlich muss dann zum Schluss auch noch die CDN-Einbindung für Chosen aus header und footer entfernt werden damit wir das endlich los sind...
Und schon hast du drei Commits zusammen - hat sich also doch gelohnt einen eigenen Branch auszumachen, was...? ;-)

**Comment by Ali-GeoFZ** [comment]
> Sehr gut, wenn das funktioniert hat! Denkst du bitte noch daran im selben Branch die ReadMe anzupassen?

Ich wusste nicht womit ich anfangen sollte für die ReadME-Datei. Die Datei muss komplett aktualisiert werden, deshalb lasse ich es erstmal so und habe dafür ein Issue #152 erstellt. Ich würde einen eigenen Branch dafür anlegen.

Der Rest ist schon fertig und gleich erstelle ich das Pull Request.
