### ISSUE TITLE
Descriptions der Schlagworte in den MSL-Thesauri werden nicht angezeigt

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#123]
Feedback aus der Sprint Review 3:
In den MSL-Thesauri fehlen die Beschreibungen. Eine Anzeige wie bei den GCMD-Thesaurus Keywords wäre hilfreich.

**Comment by McNamara84** [comment]
Ich hab mal eben kurz nachgeschaut. In unserer [Quelle](https://github.com/UtrechtUniversity/msl_vocabularies/tree/main), von der wir die MSL-Vokabularien herbekommen, gibt es leider weder eine Description noch etwas vergleichbares...

**Comment by jaFHP** [comment]
aber es gibt (zumindest bei einigen Termen) Synonyme. Deren Anzeige wäre für mich bei einer Erschließung auf jeden Fall hilfreich. Also bei mouseover wird angezeigt: "Synonyms: [...]"

**Comment by McNamara84** [comment]
Ah, jetzt verstehe ich! Ja, das ist natürlich machbar. Am einfachsten wäre es, wenn ich den API-Endpunkt anpasse damit `descriptions` bei MSL-Schlagwörtern mit den Synonymen befüllt wird, statt mit der (nicht vorhandenen) description aus der Quelle.

**Comment by McNamara84** [comment]
Notwendige Schritte:
- [ ] Route anpassen.
- [ ] Controller anpassen damit zukünftig vocabularies/combined/editor genutzt wird als Quelle.
- [ ] API-Doku anpassen.
