### ISSUE TITLE
php-Code nach PHPdoc dokumentieren

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#124]
https://www.phpdoc.de/

- [x] index.php
- [x] help.php
- [x] save_data.php
- [x] api_functions
- [x] api.php
- [x] index.php
- [x] install.php
- [x] sample_settings.php
- [x] send_feedback_mail.php
- [x] dataset_controller
- [x] general_controler
- [x] validation controller
- [x] vocab controller
- [x] save-Dateien übersetzen

**Comment by McNamara84** [comment]
api.php und api_functions.php habe ich mal als erledigt markiert, da diese beiden Dateien mittelfristig (wenn APIv2 fertig ist) nicht merh benötigt wird.

**Comment by McNamara84** [comment]
@jaFHP ich hab jetzt etwa die Hälfte gemacht. Du meintest ja, du würdest gerne auch einen Teil des PHP-Doku machen. Entsprechend würde ich den rest jetzt erstmal offen lassen.
