### ISSUE TITLE
Feedback Emails auch an Jana

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#125]
settings.php auf catsforfuture anpassen

**Comment by Ali-GeoFZ** [comment]
@McNamara84, Bitte auch an mich.

**Comment by McNamara84** [comment]
@jaFHP erhält jetzt zentral alles was uns über das Feedback-Formular übermitteln wird. @Ali-GeoFZ  damit wir alle drei das Feedback erhalten müsste ich erst die send_feedback_mail.php anpassen. Mir würde es reichen, wenn Jana das zentral bekommt. Wie ist es bei dir?

**Comment by Ali-GeoFZ** [comment]
Alles klar, dann ziehe ich mich raus davon.

**Comment by McNamara84** [comment]
Ali will nicht mehr, ich finde es auch besser, wenn das Feedback zentral bei einer Instanz auflaufen. Und falls @jaFHP mal nicht mehr möchte, ist die Änderung in der settings.php auf cats4future schnell umgesetzt. Ich schließe dann mal.
