### ISSUE TITLE
authorORCID_invalid in den lang-Dateien anpassen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#126]
Originalfeedback:
_ORCID validation has different formulations for Authors and Contributors fields. 
Contributors: 
Please enter a valid ORCID (XXXX-XXXX-XXXX-XXX(X))
Authors:
Enter a valid ORCID in the format xxxx-xx 
I liked the version from Contributors more._

-> authorORCID_invalid in den lang-Dateien anpassen

**Comment by McNamara84** [comment]
> I liked the version from Contributors more._
Finde ich gut. Wenn wir das geschickt anstellen, können wir uns damit sogar eine Sprachvariablen sparen.
