### ISSUE TITLE
DOI-Feld Hinweis sichtbarer machen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#127]
_DOI field is not required. Probably the DOI is a goal of filling out the form. Do you really need this field at all? Or maybe add a description to the field: 'If the dataset has no DOI, leave the field empty'_
 Übersetzung: 
 Das DOI-Feld ist nicht erforderlich. Wahrscheinlich ist die DOI ein Ziel beim Ausfüllen des Formulars. Brauchen Sie dieses Feld wirklich? Oder fügen Sie vielleicht eine Beschreibung zu dem Feld hinzu: „Wenn der Datensatz keinen DOI hat, lassen Sie das Feld leer“.

-> die gewünschte Info steht im Hilfetext, scheint dort also nicht prominent/sichtbar genug zu sein.

Idee 1: Hinweis prominenter platzieren. (z.B. als DOI_valid: 'If the dataset has no DOI, leave the field empty')
~Idee 2: Frage an Stakeholder: Gibt es Fälle, in denen dort eine DOI eingetragen wird? Wenn nicht, kann das Eingabefeld eigentlich weg?~

**Comment by McNamara84** [comment]
> Idee 2: Frage an Stakeholder: Gibt es Fälle, in denen dort eine DOI eingetragen wird? Wenn nicht, kann das Eingabefeld eigentlich weg?

Das Feld DOI wird auf jeden Fall benötigt. Es gibt definitiv Datensätze die neu eingeben werden, weil eine neue Version des Datensatzes eingereicht wird. Diese haben dann bereits eine DOI, bekommen dann aber eine andere Versionsnummer (1.1, 2.0, usw.). Deshalb ist das Feld DOI auch im alten MDE überhaupt vorhanden.
