### ISSUE TITLE
Feedback-Formular anpassen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#128]
Positives Feedback:
I like it very much.

Negatives Feedback:
The string above this input field.

![grafik](https://github.com/user-attachments/assets/324f059c-1d75-46f6-a6aa-7d6d36357618)
Ich vermute, es geht um diese Frage. 
Mein Vorschlag wäre: 
- die Frage konkretisieren in Richtung: 
"Was fehlt im MDE?, Was würdest du gerne noch sehen" und
"Hast du Fehler gefunden?" "Was funktioniert nicht so, wie du es erwartet hättest?"

- [x] MockUp erstellen
- [x] Im Formular umsetzen
- [x] Sending bearbeiten

**Comment by McNamara84** [comment]
Ja, da war die DeepL-Übersetzung wohl nicht ganz so optimal... Ich unterstütze den Vorschlag von @jaFHP voll und ganz.
Wollen wir den Issue gleich so erweitern, dass wir mit der Umsetzung auch gleich die entsprechenden Strings in die Sprachdateien auslagern?

**Comment by McNamara84** [comment]
Gerade gesehen: Das sind sogar schon Sprachvariablen...
