### ISSUE TITLE
Filter von NOT APPLICABLE Nodes auslagern aus der JavaScript-Datei in den API-Hook

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#13]
Aktuell wird der Filter in der Funktion filterNotApplicable() durch den Client angewendet. In der api.php würde dieser Arbeit auf der Client-Seite entfallen und der Server würde das bei der Aktualisierung der JSON-Datei gleich mt machen.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by McNamara84** [comment]
Wird gefixt mit #65 und #66 .
