### ISSUE TITLE
Publication Year uneindeutig -> Hilfetext notwendig?

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#131]
Das Publication Year können Forscher:innen bei Eintragung nicht definitiv angeben, da die Daten ja häufig eben noch nicht veröffentlicht sind. 
Es könnte z.B. den Fall geben, dass ich die Metadaten am 31.12. eines Jahres eintrage, die Publikation dann aber erst am 2.1. des nächsten Jahres erfolgt.

"If that date cannot be determined, use the date of registration" oder "If an embargo period has been in effect, use the date when the embargo period ends." wären dann wichtige und hilfreiche Informationen, oder?

https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/publicationyear/

**Comment by McNamara84** [comment]
> "If that date cannot be determined, use the date of registration" oder "If an embargo period has been in effect, use the date when the embargo period ends." wären dann wichtige und hilfreiche Informationen, oder?
> 
> https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/publicationyear/
D'accord!
