### ISSUE TITLE
Verknüpfung/Validierung ORCID + Namen bei Personenangaben (Author, Contributor)

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#132]
Als Anwenderin wäre ich sehr glücklich, wenn ich einfach meine ORCID eingeben könnte, und die Namensfelder dann automatisch ausgefüllt würden. So würden Fehler in der ORCID evtl auch eher auffallen. Wenn das umgesetzt werden kann, würde ich vorschlagen, die Feldreihenfolge zu verändern: ORCID, Nachname, Vorname, Affiliation

**Comment by McNamara84** [comment]
Halte ich für eine sehr gute Idee! Ich hab jetzt nicht so tief geschaut, aber [orcid.org bietet offensichtlich eine API an](https://info.orcid.org/documentation/api-tutorials/api-tutorial-read-data-on-a-record/).
Ich versuche mal bis zum nächsten Sprint Planning mich einzulesen und den Aufwand grob abzuschätzen.

**Comment by McNamara84** [comment]
Vorgehen:
- [ ] Umbau Frontend (Input für ORCID nach vorne umziehen).
- [ ] Event Listener auf ORCID Input legen.
- [ ] API Call schreiben.
- [ ] ReadMe anpassen.
- [ ] Guide anpassen

**Comment by McNamara84** [comment]
Event Listener doch lieber auf [blur Event](https://www.perplexity.ai/search/was-ist-das-blur-event-in-jque-us9_GTQsSSKI3aZMABH_9A) legen? Zu viele Anfragen, wenn geprüft wird nach dem 10. Zeichen...
