### ISSUE TITLE
Validierung der Koordinaten überarbeiten

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#136]
Bei der Validierung der Koordinaten in TSC werden auch ungültige Koordinaten wie z. B. als Breitengrad -91° akzeptiert. Das soll natürlich nicht so sein - Breitengrade gehen nur von -90 bis +90 und Längengrade von -180 bis +180

kann teil-gelöst werden durch besseren Hilfetext in #101 
Komplett-Lösung noch nicht vorhanden

**Comment by McNamara84** [comment]
Ich hab jetzt mehrfach versucht dieses Problem zu reproduzieren. Klar, man kann schon manuell falsche Koordinaten eingeben und dann die Karte öffnen. Aber spätestens beim Klick auf "Save" werden die falschen Koordinaten bemängelt. Also der RegEx für Long und Lat stimmen.
Soll hier wirklich das PopUp/Modal mit der Karte nicht mehr aufgehen, wenn invalide Koordinaten eingegeben werden?

**Comment by jaFHP** [comment]
Vorschlag: Issue wird abgelehnt.

**Comment by McNamara84** [comment]
> Vorschlag: Issue wird abgelehnt.

Dafür. Erstmal würde mir ausreichen, wenn wir diesen Issue in den nächsten Sprint schieben könnten.

**Comment by jaFHP** [comment]
> > Vorschlag: Issue wird abgelehnt.
> 
> Dafür. Erstmal würde mir ausreichen, wenn wir diesen Issue in den nächsten Sprint schieben könnten.

mach ich.
