### ISSUE TITLE
Selenium-Tests automatisieren

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#143]
Eine Automatisierung der Selenium-Tests über GitHub Actions wäre schick. Und zeitersparend.

**Comment by McNamara84** [comment]
Installieren von Chrome in Ubuntu:
`sudo apt-get install -y chromium-browser chromium-chromedriver`

**Comment by McNamara84** [comment]
Selenium IDE CLI unter Ubuntu installieren:
`npm install -g selenium-side-runner`

node.js installieren?

**Comment by McNamara84** [comment]
Hab ich in diesem Sprint leider nicht geschafft. Schiebe das deshalb in den nächsten.
