### ISSUE TITLE
Diakritika werden in formgroup "Originating Laboratory" nicht richtig angezeigt

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#144]
Beispiele:
![grafik](https://github.com/user-attachments/assets/1ec1fd95-7abc-429d-8724-83e073922725)
![grafik](https://github.com/user-attachments/assets/6b1e0286-d814-4fc6-87e8-300e658bab0f)

Bei den Affiliations von Authors etd. funktionierts.
Im Projekt letztes Semester gab es auch ein Problem mit diakritischen Zeichen, vielleicht hilft das: https://github.com/McNamara84/gfz-metadata-editor-v2/issues/101

**Comment by McNamara84** [comment]
E-Mail an L. gesendet.

**Comment by McNamara84** [comment]
Antwort von L.:
> I can see the encoding issue being present in the lab vocabulary on GitHub. Next week I will not be available to correct this issue but I will look into it when I return. We are in the process of updating the workflow to generate this vocabulary and hope to implement it in December.
At the moment I think it is not needed to use the affiliation data from the lab vocabulary as it contents are not maintained.

Ich schiebe den Issue deshalb erstmal in den nächsten Sprint, da wir das in diesem Sprint nicht aufgelöst bekommen.

**Comment by jaFHP** [comment]
Problem sollte an der Wurzel gelöst werden, s.o.
