### ISSUE TITLE
fg Originating Laboratory: Eingabefeld Laboratory Name hat keine ID

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#148]
oder ich übersehe sie??

**Comment by jaFHP** [comment]
Da ich sie zum Ansprechen in Selenium haben will, würde ich mir die morgen mal vornehmen. und vllt die einfachen Anpassungen die ich eben in Issues #147 #146 #145 #144  aufgeschrieben hatte auch umsetzen. 
Oder hat da jemand was dagegen @Ali-GeoFZ @McNamara84 ? Ich kenne die Stakeholderwünsche bzgl dieses Feldes noch nicht.

**Comment by Ali-GeoFZ** [comment]
@jaFHP, ich hab nichts dagegen, viel spaß damit.

**Comment by Ali-GeoFZ** [comment]
> oder ich übersehe sie??

Du hast Recht  da ist ein Tippfehler glaub ich.
![Screenshot 2024-11-05 174937](https://github.com/user-attachments/assets/cf2c9b0f-8b63-407a-a79b-4c3e1c3e3eda)

**Comment by McNamara84** [comment]
> Da ich sie zum Ansprechen in Selenium haben will, würde ich mir die morgen mal vornehmen. und vllt die einfachen Anpassungen die ich eben in Issues #147 #146 #145 #144 aufgeschrieben hatte auch umsetzen. Oder hat da jemand was dagegen @Ali-GeoFZ @McNamara84 ? Ich kenne die Stakeholderwünsche bzgl dieses Feldes noch nicht.

Ich wäre sogar ganz froh, wenn du uns so etwas abnimmst. Auch wenn wir das nicht in diesem Sprint eingeplant hatten, heißt das nicht, dass die niemand bearbeiten darf. Was weg ist ist weg. Insofern: Danke!
