### ISSUE TITLE
Eingabefeld Lab Affiliation aus GUI entfernen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#151]
Die Affiliations der 118 MSL-Labs stehen ja fest und sollen durch Anwender:innen wahrscheinlich nicht geändert werden.

Nach meinem Verständnis ist das Eingabefeld **inputLaboratoryAffiliation** dann nicht notwendig, bzw. sogar eine potentielle Quelle für Inkonsistenzen. Denn im Moment können Anwender:innen die Affiliations verändern und damit falsche Daten produzieren. 

Vorschlag 1: Das Feld wird automatisch befüllt wie bisher, die Eingabe kann aber nicht bearbeitet werden. 
-> Fänd ich ok, aber mir erschließt sich der Sinn nicht so ganz. Ist das eine Info, die Anwender:innen brauchen?

Vorschlag 2: Das Feld kommt ganz raus und wird ein _hidden_ field.
-> Finde ich eleganter. Aber wieder die Frage: brauchen Anwender:innen vielleicht die Affiliations Info? Dann ginge das nicht.

**Comment by McNamara84** [comment]
E-Mail an L. gesendet.

**Comment by jaFHP** [comment]
Antwort von L.: At the moment I think it is not needed to use the affiliation data from the lab vocabulary as it contents are not maintained.
-> Affiliation Speichern, Feld muss nicht sichtbar sein. Umsetzung von Vorschlag 2
