### ISSUE TITLE
fg Rights: Bei ResourceType=Software wird eine falsche Lizenz angezeigt

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#160]
Creative Commons Attribution 4.0 International ist forSoftware=0, sollte also nicht in der Dropdownauswahl auftauchen, wenn ResourceType=Software. Zur Zeit tut sie das aber. 

Vielleicht hat das etwas damit zu tun, dass die CC-Lizenz als default Option gesetzt wurde?

![grafik](https://github.com/user-attachments/assets/9aed05b4-a881-494f-b7c3-dc0bf5d9de05)

![grafik](https://github.com/user-attachments/assets/37682592-84a1-4a64-af75-8cb0b54f5438)

**Comment by McNamara84** [comment]
Weil es so schön in meinen Branch passt... ;-)
