### ISSUE TITLE
Top Terms in MSL Thesaurus umbenennen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#166]
von R.:
_Finally – a point that I’m guessing will require an action on our side: I see that the top terms in the keyword selector are abbreviated versions of the actual terms (e.g. “analogue” refers to “analogue modelling of geological processes”). @L. – is this indeed on our side? If so – can you perhaps fix this?_

"Geologicalage" sollte z.B. auch noch ein Leerzeichen spendiert bekommen.
Richtige Benennung steht hier: https://epos-msl.uu.nl/vocabularies

**Comment by McNamara84** [comment]
Hier würde ich gerne die Reaktion von L. abwarten und den Issue auf jeden Fall in den nächsten Sprint schieben.

**Comment by McNamara84** [comment]
Wird zusammen mit #123 gefixt.
