### ISSUE TITLE
Mapping 2ISO: Leere DOI wird im ISO-Schema gespeichert

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#171]
Wenn im MDE2 keine DOI angegeben wird, wird das XML-Element <fileIdentifier> trotzdem erzeugt und es wird der Präfix trotzdem gespeichert. Ich bin der Meinung, dass jedoch kein Präfix gespeichert werden sollte und möglichst auch gar nicht erst das XML-Element selbst geschrieben werden sollte.

Aktuelles Beispiel, wenn keine DOI eingegeben wurde:
```
<fileIdentifier>
    <gco:CharacterString>doi:</gco:CharacterString>
</fileIdentifier>
```

ähnlich zu #172

**Comment by jaFHP** [comment]
stand jetzt wird ein leeres xml Element erzeugt.
