### ISSUE TITLE
Mapping 2Datacite: Leere Embargo until wird als 0000-00-00 gespeichert

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#172]
Wenn man beim Ausfüllen des MDE2 das Feld Embargo unitil nicht befüllt (kommt sehr häufig vor), wir im DataCiteSchema
`<date dateType="Available">0000-00-00</date>`
gespeichert.
Damit es zu keinem Fehler kommt, wenn die XML-Datei an DataCite übermittelt wird, schlage ich vor das Mapping anzupassen damit das Feld in solchen Fällen gar nicht erst gespeichert wird (auch nicht leer).

**Comment by jaFHP** [comment]
Ich bekomme grade einfach ein leeres Element:

<date dateType="Available"/>
