### ISSUE TITLE
Changelog gewünscht / Versionsänderungen öffentlich machen

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#180]
_I wanted to test the new features, but unfortunately it is not possible to show the latest changes since the last meeting. It would be nice to have something like a changelog with the most important changes. This would help me with testing if new improvements were made._

siehe auch #170

**Comment by McNamara84** [comment]
Guter Punkt. Vielleicht einen Punkt "Changelog" im ?-Menü ergänzen. Dieser könnte ein Modal öffnen, das den Changelog für die letzten drei? Versionen anzeigt. Vielleicht könnten wir dorthin auch #170 auslagern?
