### ISSUE TITLE
In der generierten XML-Datei fehlt  titleType="" für Main Title

### ISSUE THREAD

**Issue by Ali-GeoFZ** [McNamara84/gfz-metadata-editor-msl-v2#197]
In der generierten XML-Datei wird der Haupttitel nicht korrekt dargestellt.

![Screenshot 2024-11-21 215012](https://github.com/user-attachments/assets/5e65162f-6540-4bb0-8c74-66e94c8f70c4)

**Comment by McNamara84** [comment]
@Ali-GeoFZ , ich kann den Fehler leide nicht sehen. So wie es in deinem Screenshot angezeigt wird ist es doch richtig, oder? Wo siehst du da einen Fehler? Ein leeres Attribut `titleType=""` bei einem Main Title halte ich weder für sinnvoll noch finde ich das von DataCite so vorgegeben in der Doku...

**Comment by Ali-GeoFZ** [comment]
> @Ali-GeoFZ , ich kann den Fehler leide nicht sehen. So wie es in deinem Screenshot angezeigt wird ist es doch richtig, oder? Wo siehst du da einen Fehler? Ein leeres Attribut `titleType=""` bei einem Main Title halte ich weder für sinnvoll noch finde ich das von DataCite so vorgegeben in der Doku...

Stimmt, so ist es richtig. Ich habe mir jetzt die Dokumentation nochmal angeschaut. Sorry für die Verwirrung!
