### ISSUE TITLE
Load XML-implementieren

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#200]
- [x] Eventhandler für Load-Button
- [ ] Modal erstellen mit Dateiauswahl und ggf #43 
- [ ] XML-Datei in xml-string umwandeln
- [ ] an php-Funktion übergeben
- [ ] Mapping erstellen (MapForce xml-3Schema-Datei auf Freestyle) und XSLT-Datei erstellen (alternativ mit js)
- [ ] XSLT-Datei durch php-Funktion ausführen

**Comment by McNamara84** [comment]
Wie abgesprochen würde ich hier das Backend machen. Ich nutze dafür den Branch `feature/load-xml-backend`.
Vorschläge zur Benennung der anderen beiden Branches wäre `feature/load-xml-mapping` für @jaFHP und `feature/load-xml-frontend` für @Ali-GeoFZ , wenn das für euch okay ist.
