### ISSUE TITLE
Mapping 2DataCite: freeKeywords "EPOS" und "multi-scale Laboratories" werden als subjects gemappt

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#208]
...obwohl sie im MDE nicht angegeben wurden. Beim Laden in z.B. den alten MDE erscheinen sie dann folgerichtig als free Keywords.
War das ein Wunsch von Stakeholdern, oder ist das ein bug?

![grafik](https://github.com/user-attachments/assets/567729a7-943e-4cbb-aeed-448857734214)

**Comment by McNamara84** [comment]
Tatsächlich tragen das wohl die Datenkurator:innen bislang händisch nach. Der aktuelle Metadateneditor macht das nicht. Ich hatte mir mir von @sefrenzel mal einen kuratierten Original-Datensatz schicken lassen. Leite ich gleich weiter an dich und @Ali-GeoFZ .
