### ISSUE TITLE
fg STC: wird nur in DB gespeichert, wenn Uhrzeiten eingegeben werden

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#217]
Uhrzeiten sind aber kein Pflichtfeld (mehr)

**Comment by McNamara84** [comment]
@qs-team bzw. @jaFHP 😜: Aktuell werden die beiden Dates zusammen mit den Times in der Datenbank gemeinsam gespeichert als DateTime-Datentyp. Um jetzt nicht das Datenbankschema anpassen damit wir Date und Time getrennt speichern können, würde ich gerne vorschlagen als Default-Wert für die Startuhrzeit 00:00:00 und als default-Wert für die Enduhrzeit 23:59:59 im Zeitstempel anzugeben. Dies würde aber evtl. etwas mehr Aufmerksamkeit beim Mapping erfordern, so weit ich das vorhersehen kann. Deshalb die Frage an das QS-Team: Wäre es okay für dich, wenn ich das so umsetze?

**Comment by McNamara84** [comment]
> > > > [@QS-Team](https://github.com/QS-Team) bzw. [@jaFHP](https://github.com/jaFHP) 😜: Aktuell werden die beiden Dates zusammen mit den Times in der Datenbank gemeinsam gespeichert als DateTime-Datentyp. Um jetzt nicht das Datenbankschema anpassen damit wir Date und Time getrennt speichern können, würde ich gerne vorschlagen als Default-Wert für die Startuhrzeit 00:00:00 und als default-Wert für die Enduhrzeit 23:59:59 im Zeitstempel anzugeben. Dies würde aber evtl. etwas mehr Aufmerksamkeit beim Mapping erfordern, so weit ich das vorhersehen kann. Deshalb die Frage an das QS-Team: Wäre es okay für dich, wenn ich das so umsetze?
> > > 
> > > 
> > > Ich würde ungern "falsche" Angaben speichern. Die Angabe einer Zeit impliziert dann eine Information, die eigentlich nicht vorhanden ist. Das halte ich für falsch.
> > 
> > 
> > Okay, dann müssen wir die beiden DateTime Felder auseinander nehmen. [@Ali-GeoFZ](https://github.com/Ali-GeoFZ) , magst du die DB-Struktur anpassen oder soll ich?
> 
> Ja, Ich kümmere mich darum!

Okay. Ich hab uns oben einen kleinen "Fahrplan" erstellt. Zweiter Beitrag von oben.

**Comment by McNamara84** [comment]
> Vorschlag: Ich mache das im Mapping im Mapping Branch, dann kann ich diesen hier reviewen.

Klar, gerne! Du kannst dir ja die frisch erzeugte neue Freestyle-XML samt Schema rüber kopieren.
