### ISSUE TITLE
Mapping 2ISO: language Element nicht richtig gemappt

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#222]
Neu:
![grafik](https://github.com/user-attachments/assets/014d13b7-22c2-4d88-a972-2ed70038682b)
alt:
![grafik](https://github.com/user-attachments/assets/cc623809-a6f6-47ce-93e3-dc4bdd8f4908)

wo das eng im alten MDE herkommt ist mir allerdings auch nicht klar.

**Comment by McNamara84** [comment]
> wo das eng im alten MDE herkommt ist mir allerdings auch nicht klar.

Ich behaupte mal, das ist eine Konstante, denn auch wenn man die Sprache im alten MDE ändert auf z. B. Deutsch, dann wird dort trotzdem noch eng gespeichert.
