### ISSUE TITLE
fg STC: Feldgrößen der Date/Time Felder stimmen in geklonten Zeilen nicht

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#234]
![grafik](https://github.com/user-attachments/assets/581a7452-416a-4fbd-8ef0-b9c6b3e0e9f9)

**Comment by Ali-GeoFZ** [comment]
Form groups:

- [ ] Resource Information
- [ ] Author(s)
- [ ] Contact Person(s)
- [ ] Originating Laboratory
- [ ] Contributors
- [ ] Spatial and Temporal Coverages
- [ ] Related work
- [ ] Funding Reference
