### ISSUE TITLE
Originating Laboratories werden nicht gespeichert

### ISSUE THREAD

**Issue by jaFHP** [McNamara84/gfz-metadata-editor-msl-v2#241]
das muss passieren, bevor gemappt werden kann

**Comment by McNamara84** [comment]
Fixed in fix-export-xml. Problem mit der Speicherung von ROR IDs bleibt natürlich, da nur die wenigsten Affiliations in der Quelle nach Vorzugsbenennung beannt wurden und damit in AffiliationData nur schwer der korrekte Eintrag ermittelbar ist. Der Issue an sich ist aber gefixt.
