### ISSUE TITLE
Speicherung der neuen MSL-Thesauri in der Datenbank implementieren

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#47]
**General**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Analogue modelling of geological processes**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Geochemistry**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Microsocopy and tomography**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Paleomagnetism**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Rock and melt physics**
- [x] Tabelle erstellen und Datensätze einfügen
- [x] Speicherung implementieren
- [x] Dokumentation erweitern

**Comment by Ali-GeoFZ** [comment]
- [ ] ER-Modell prüfen, ob es erweitert werden muss
- [ ] Falls nötig, ER-Modell erweitern
- [ ] Falls nötig, install.php erweitern um Installationsroutine für aktualisierte Datenbankstruktur gem. ER-Modell
- [ ] install.php um Hinzufügen von testdatensätze erweitern
- [ ] Dokumentation erweitern

**Comment by McNamara84** [comment]
Wird jetzt gespeichert.
