### ISSUE TITLE
Prüfen, ob Datenbankattribute besser nach schema.org umbenannt werden sollten

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#49]
schema.org gilt als die Referenz für Attribute zu Personen, Organisationen, etc. Standardisierung für unsere Datenbank nach diesen Vorgaben sinnvoll?

- [x] Prüfen, ob Datenbankattribute besser nach schema.org aussehen
- [x] Entscheidung über unsere Vorgaben (im Daily ansprechen!)
- [ ] ggf. umsetzen in neuem Issue

**Comment by McNamara84** [comment]
@Ali-GeoFZ , wie sieht es hier aus. Sehe ich das richtig, dass wir diesen Issue vielleicht auch besser schieben?

**Comment by Ali-GeoFZ** [comment]
ja, besser
