### ISSUE TITLE
Abstand der Eingabefelder zum Rand der Bootstrap Cards angleichen

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#5]
Innerhalb der Kärtchen sollte die margin-top und margin-bottom der Eingabefelder zum Kartenrand genauso groß sein wie zu den Seiten.
Derzeit sind die Abstände etwas größer als zu den Seiten. Wenn ihr die Abstände nach oben und unten ein wenig verkleinert, spart das Platz und sieht aufgeräumter aus.

**Comment by jaFHP** [comment]
Die margins kommen doch aus Bootstrap, oder? Würde da ungern ran, da wird sich jemand was bei gedacht haben.
