### ISSUE TITLE
ReadMe (technische Dokumentation) überarbeiten

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#7]
Vollständige Überarbeitung der kompletten (technischen) Dokumentation in der ReadMe.

- [x] Linktexte wie "Link zur Dokumentation von DataCite mit der Beschreibung des Elements im Metadaten-Schema" halte ich persönlich für zu lang. Dass es sich um einen Link handelt, sollte für die Zielgruppe der ReadMe bekannt sein. ;-) Da fände ich so etwas wie "Erklärung von DataCite" o. ä. deutlich komakter.
- [x] ...

**Comment by Ali-GeoFZ** [comment]
done!
