### ISSUE TITLE
MSL-Thesauri zusammenführen

### ISSUE THREAD

**Issue by McNamara84** [McNamara84/gfz-metadata-editor-msl-v2#91]
Alle 6 MSL-Thesauri (nicht GCDM und auch nicht Originating Laboratories) zusammenführen in eine Form Group, in der dann alle kontrollierten Vokabularien angezeigt werden.
- [x] API-Funktion umschreiben, so dass nur noch eine JSON-Datei msl-vocalbularies.json zwischengespeichert wird im Ordner /JSON
- [x] MockUp in Figma überarbeiten
- [x] Alle Acordeons entfernen und zu einer normalen Form Group (wie bei Thesaurus Keywords)
- [x] jsTree fixen damit Baumstruktur der Thesauri alle auf einmal angezeigt werden (ausklappbar)
- [x] Speicherung überarbeiten
- [x] Test für Speicherung anpassen
- [x] Dokumentation

**Comment by McNamara84** [comment]
Ich habe den API-Endpunkt umgeschrieben. Die Datei wird jetzt als json/msl-vocalbularies.json angelegt wie besprochen. @Ali-GeoFZ du könntest also jetzt mit der Zusammenführung beginnen und die Acordeons entfernen in einem nächsten Commit.

**Comment by McNamara84** [comment]
Ich passe gleichzeitig die API-Dokumentation an.

**Comment by McNamara84** [comment]
Die Idee von den Stakeholdern kam auch nochmal über das Feedback-System rein. original-Nachricht:

> As discussed with Ronald it could be helpful to not ask for specific keywords per section but just present the entire vocabulary(ies) tree in one go making it easier for people to select multiple keywords in one go.

Wie mit Ronald besprochen, könnte es hilfreich sein, nicht nach spezifischen Schlüsselwörtern pro Abschnitt zu fragen, sondern einfach den gesamten Vokabularbaum in einem Durchgang zu präsentieren, um es den Leuten zu erleichtern, mehrere Schlüsselwörter in einem Durchgang auszuwählen.

**Comment by Ali-GeoFZ** [comment]
Issue abgeschloßen!
