### ISSUE TITLE
Mapping von FreestyleXML nach DataCite

### ISSUE THREAD

**Issue by Ali-GeoFZ** [McNamara84/gfz-metadata-editor-msl-v2#94]
Folgende Form groups müssen von FreestyleXML nach DataCite gemappt werden:

- [x] Mapping von FreestyleXML nach DataCite für Resource Information
- [x] Mapping von FreestyleXML nach DataCite für Licenses and Rights
- [x] Mapping von FreestyleXML nach DataCite für Authors 
- [x] Mapping von FreestyleXML nach DataCite für Contact Person 
- [x] Mapping von FreestyleXML nach DataCite für Originaring Laboratory 
- [x] Mapping von FreestyleXML nach DataCite für Contributors 
- [x] Mapping von FreestyleXML nach DataCite für Descriptions 
- [x] Mapping von FreestyleXML nach DataCite für MSL-Thesaurus 
- [x] Mapping von FreestyleXML nach DataCite für Thesaurus Keywords
- [x] Mapping von FreestyleXML nach DataCite für Free Keywords
- [x] Mapping von FreestyleXML nach DataCite für Dates
- [x] Mapping von FreestyleXML nach DataCite für Spatial and Temporal Coverages
- [x] Mapping von FreestyleXML nach DataCite für Related work
- [x] Mapping von FreestyleXML nach DataCite für Funding Reference

**Comment by McNamara84** [comment]
@Ali-GeoFZ, willst du wirklich alle 3 Mappings alleine machen? Willst du dieses hier vielleicht mir überlassen damit wir das Hauptziel für diesen Sprint ach auf jeden Fall schaffen?

**Comment by McNamara84** [comment]
Mapping aller Datenbankattribute abgeschlossen.
