### ISSUE TITLE
Mapping von FreestyleXML nach ISO

### ISSUE THREAD

**Issue by Ali-GeoFZ** [McNamara84/gfz-metadata-editor-msl-v2#97]
Folgende Form groups müssen von FreestyleXML nach ISO gemappt werden:

- [x] Mapping von FreestyleXML nach ISO für Resource Information
- [x] Mapping von FreestyleXML nach ISO für Licenses and Rights
- [x] Mapping von FreestyleXML nach ISO für Authors 
- [x] Mapping von FreestyleXML nach ISO für Contact Person 
- [x] Mapping von FreestyleXML nach ISO für Originaring Laboratory 
- [x] Mapping von FreestyleXML nach ISO für Contributors 
- [x] Mapping von FreestyleXML nach ISO für Descriptions 
- [x] Mapping von FreestyleXML nach ISO für MSL-Thesaurus 
- [x] Mapping von FreestyleXML nach ISO für Thesaurus Keywords
- [x] Mapping von FreestyleXML nach ISO für Free Keywords
- [x] Mapping von FreestyleXML nach ISO für Dates
- [x] Mapping von FreestyleXML nach ISO für Spatial and Temporal Coverages
- [x] Mapping von FreestyleXML nach ISO für Related work
- [x] Mapping von FreestyleXML nach ISO für Funding Reference

**Comment by McNamara84** [comment]
[Doku zu ISO/GMD-Schema](https://schemas.isotc211.org/19139/-/gmd/1.0/gmd/)

**Comment by McNamara84** [comment]
Workaround für die Zusammenführung aller 4 <description>-Elemente zu einem <abstract>-Element:
```
<abstract>
    <CharacterString>
        <xsl:for-each select="*[local-name()='Descriptions' and namespace-uri()='']/*[local-name()='Description' and namespace-uri()='']">
            <xsl:if test="position() &gt; 1">
                <!-- Fügt einen Zeilenumbruch zwischen den Beschreibungen hinzu -->
                <xsl:text>&#xA;&#xA;</xsl:text>
            </xsl:if>
            <xsl:value-of select="*[local-name()='description' and namespace-uri()='']"/>
        </xsl:for-each>
    </CharacterString>
</abstract>
```

Dieses Element muss entsprechend in der exportierten XSLT-Datei ersetzt werden damit die Transformation korrekt funktioniert!

**Comment by McNamara84** [comment]
Das Mapping der Thesaurus Keywords wird noch etwas dauern.

**Comment by McNamara84** [comment]
Mapping abgeschlossen. Feinschliff ist sicherlich noch nötig, wenn der gesamte Stack an XSLT-Dateien zusammen die Transformation durchführt.

**Comment by McNamara84** [comment]
Erledigt.
