### ISSUE TITLE
Mapping von FreestyleXML nach DIF

### ISSUE THREAD

**Issue by Ali-GeoFZ** [McNamara84/gfz-metadata-editor-msl-v2#98]
Folgende Form groups müssen von FreestyleXML nach DIF gemappt werden:

- [x] Mapping von FreestyleXML nach DIF für Resource Information
- [x] Mapping von FreestyleXML nach DIF  für Licenses and Rights
- [x] Mapping von FreestyleXML nach DIF für Authors 
- [x] Mapping von FreestyleXML nach DIF für Contact Person 
- [x] Mapping von FreestyleXML nach DIF für Originaring Laboratory 
- [x] Mapping von FreestyleXML nach DIF für Contributors 
- [x] Mapping von FreestyleXML nach DIF für Descriptions 
- [x] Mapping von FreestyleXML nach DIF für MSL-Thesaurus 
- [x] Mapping von FreestyleXML nach DIF für Thesaurus Keywords
- [x] Mapping von FreestyleXML nach DIF für Free Keywords
- [x] Mapping von FreestyleXML nach DIF für Dates
- [x] Mapping von FreestyleXML nach DIF für Spatial and Temporal Coverages
- [x] Mapping von FreestyleXML nach DIF für Related work
- [x] Mapping von FreestyleXML nach DIF für Funding Reference

**Comment by McNamara84** [comment]
Also das Mapping für die description-Eingabefelder kann so nicht funktionieren. Im if-Block existiert zwar eine Bedingung, aber egal ob sie erfüllt wird oder nicht, wird nichts ausgeführt.

**Comment by Ali-GeoFZ** [comment]
ich habe nicht ganz verstanden was du damit meinst aber bei mir funktioniert das ganz gut es wird geprüft, um welchen Description-Typ es sich handelt. Wenn der Typ 'abstrakt' ist, wird er in der Ausgabe angezeigt. Bei allen anderen Description-Typen wird er einfach ignoriert. und so sieht's aus
![Screenshot 2024-10-22 084022](https://github.com/user-attachments/assets/72afd482-43a6-44cb-b081-9e4107094bfb)

**Comment by McNamara84** [comment]
> ich habe nicht ganz verstanden was du damit meinst aber bei mir funktioniert das ganz gut es wird geprüft, um welchen Description-Typ es sich handelt. Wenn der Typ 'abstrakt' ist, wird er in der Ausgabe angezeigt. Bei allen anderen Description-Typen wird er einfach ignoriert. und so sieht's aus ![Screenshot 2024-10-22 084022](https://github.com/user-attachments/assets/72afd482-43a6-44cb-b081-9e4107094bfb)

So kann das Ergebnis nicht aussehen mit deinem Commit. Vielleicht hast du vor dem Commit nicht gespeichert oder es erst nach dem Commit geändert, aber aktuell sind bei Eingänge des if-Blocks (true und false) nicht belegt:
![Image](https://github.com/user-attachments/assets/e0557c43-11c2-4ecf-9771-4a1a0878eca2)

**Comment by Ali-GeoFZ** [comment]
Du hattest recht, mein Commit war nicht vollständig Commited, kannst du bitte noch einmal überprüfen, ob es jetzt bei dir funktioniert?

**Comment by McNamara84** [comment]
> Du hattest recht, mein Commit war nicht vollständig Commited, kannst du bitte noch einmal überprüfen, ob es jetzt bei dir funktioniert?

Ja, jetzt sieht es gut aus.

**Comment by McNamara84** [comment]
Kannst du dir das Mapping von TSC nochmal anschauen? Das hast du ja ganz gut nachgebaut, aber sobald du einen Punkt statt einer Box bekommst (also nur Min ausgefüllt wird bei den Koordinaten), dann erhältst du folgendes Ergebnis:
![Image](https://github.com/user-attachments/assets/11a7a56c-7e6d-432d-bb78-2ba780c4e8cd)

**Comment by McNamara84** [comment]
Snippet für die Transformation von mehreren Author-Elementen in ein Dataset_Creator-Element, getrennt durch Semikolons:
```
<Data_Set_Citation>
    <Dataset_Creator>
        <xsl:for-each select="*[local-name()='Authors' and namespace-uri()='']/*[local-name()='Author' and namespace-uri()='']">
            <xsl:value-of select="concat(*[local-name()='familyname' and namespace-uri()=''], ', ', *[local-name()='givenname' and namespace-uri()=''])"/>
            <xsl:if test="position() != last()">
                <xsl:text>; </xsl:text>
            </xsl:if>
        </xsl:for-each>
    </Dataset_Creator>
    <xsl:for-each select="(./*[local-name()='Titles' and namespace-uri()='']/*[local-name()='Title' and namespace-uri()=''])[contains(*[local-name()='type' and namespace-uri()=''], 'Main Title')]">
        <xsl:variable name="var5_filter" select="."/>
        <Dataset_Title>
            <xsl:value-of select="*[local-name()='text' and namespace-uri()='']"/>
        </Dataset_Title>
    </xsl:for-each>
    <Dataset_Release_Date>
        <xsl:value-of select="*[local-name()='year' and namespace-uri()='']"/>
    </Dataset_Release_Date>
</Data_Set_Citation>
```
<Data_Set_Citation> muss entsprechend nach dem Export aus MapForce in der dann entstandenen XSLT-Datei ausgetauscht werden.

**Comment by McNamara84** [comment]
Das Mapping ist damit wohl vollständig.
